users:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: 127.0.0.1
      port: 7442
      user: postgres
      pass: postgres
      dbname: postgres
      schema: target
  target: dev
