users:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: 127.0.0.1
      port: 5432
      user: postgres
      pass: changeme
      dbname: postgres
      schema: target
  target: dev
